export const defaultCategoryIcon = 'i-lucide-folder'

export const primaryCategoryIconCount = 12

export const categoryIconOptions = [
  { name: defaultCategoryIcon, label: '文件夹' },
  { name: 'i-lucide-code-xml', label: '代码' },
  { name: 'i-lucide-terminal', label: '终端' },
  { name: 'i-lucide-brain-circuit', label: '思考' },
  { name: 'i-lucide-sparkles', label: '灵感' },
  { name: 'i-lucide-book-open', label: '阅读' },
  { name: 'i-lucide-pen-tool', label: '写作' },
  { name: 'i-lucide-image', label: '图片' },
  { name: 'i-lucide-camera', label: '摄影' },
  { name: 'i-lucide-palette', label: '设计' },
  { name: 'i-lucide-coffee', label: '生活' },
  { name: 'i-lucide-rocket', label: '项目' },
  { name: 'i-lucide-cpu', label: '系统' },
  { name: 'i-lucide-bot', label: '智能' },
  { name: 'i-lucide-server', label: '服务器' },
  { name: 'i-lucide-cloud', label: '云服务' },
  { name: 'i-lucide-database', label: '数据' },
  { name: 'i-lucide-network', label: '网络' },
  { name: 'i-lucide-binary', label: '算法' },
  { name: 'i-lucide-braces', label: '开发' },
  { name: 'i-lucide-bug', label: '调试' },
  { name: 'i-lucide-git-branch', label: '版本' },
  { name: 'i-lucide-github', label: '开源' },
  { name: 'i-lucide-smartphone', label: '移动端' },
  { name: 'i-lucide-monitor', label: '桌面端' },
  { name: 'i-lucide-layers-3', label: '架构' },
  { name: 'i-lucide-box', label: '组件' },
  { name: 'i-lucide-package', label: '资源包' },
  { name: 'i-lucide-workflow', label: '工作流' },
  { name: 'i-lucide-wrench', label: '工具' },
  { name: 'i-lucide-settings', label: '设置' },
  { name: 'i-lucide-hammer', label: '实践' },
  { name: 'i-lucide-lock-keyhole', label: '安全' },
  { name: 'i-lucide-shield-check', label: '防护' },
  { name: 'i-lucide-key-round', label: '权限' },
  { name: 'i-lucide-newspaper', label: '资讯' },
  { name: 'i-lucide-notebook-tabs', label: '笔记' },
  { name: 'i-lucide-lightbulb', label: '知识' },
  { name: 'i-lucide-graduation-cap', label: '教育' },
  { name: 'i-lucide-school', label: '学习' },
  { name: 'i-lucide-languages', label: '语言' },
  { name: 'i-lucide-chart-no-axes-combined', label: '分析' },
  { name: 'i-lucide-briefcase-business', label: '职场' },
  { name: 'i-lucide-shopping-bag', label: '商业' },
  { name: 'i-lucide-badge-dollar-sign', label: '财经' },
  { name: 'i-lucide-users', label: '社区' },
  { name: 'i-lucide-message-circle', label: '交流' },
  { name: 'i-lucide-calendar-days', label: '日程' },
  { name: 'i-lucide-clock-3', label: '时间' },
  { name: 'i-lucide-bookmark', label: '收藏' },
  { name: 'i-lucide-archive', label: '归档' },
  { name: 'i-lucide-music', label: '音乐' },
  { name: 'i-lucide-headphones', label: '音频' },
  { name: 'i-lucide-podcast', label: '播客' },
  { name: 'i-lucide-film', label: '影视' },
  { name: 'i-lucide-gamepad-2', label: '游戏' },
  { name: 'i-lucide-map', label: '旅行' },
  { name: 'i-lucide-plane', label: '出行' },
  { name: 'i-lucide-utensils', label: '美食' },
  { name: 'i-lucide-dumbbell', label: '运动' },
  { name: 'i-lucide-stethoscope', label: '健康' },
  { name: 'i-lucide-microscope', label: '科学' },
  { name: 'i-lucide-telescope', label: '探索' },
  { name: 'i-lucide-leaf', label: '自然' },
  { name: 'i-lucide-sprout', label: '成长' },
  { name: 'i-lucide-paw-print', label: '宠物' },
  { name: 'i-lucide-house', label: '居家' },
  { name: 'i-lucide-heart', label: '随笔' },
  { name: 'i-lucide-star', label: '精选' },
  { name: 'i-lucide-flame', label: '热门' },
  { name: 'i-lucide-zap', label: '效率' }
] as const

export function visibleCategoryIcons(selectedIcon: string, expanded: boolean) {
  if (expanded) return categoryIconOptions
  const primary = categoryIconOptions.slice(0, primaryCategoryIconCount)
  const selected = categoryIconOptions.find(option => option.name === selectedIcon)
  return selected && !primary.includes(selected) ? [...primary, selected] : primary
}
